### PR TITLE
(bknd) vendor product management   update #319

### PR DESCRIPTION
**Pull request by multiminparvo**
https://github.com/bounswe/bounswe2020group4/issues/319 
Vendor should be able to aupdate the product infos.

Mongoose and Mongodb is not able to update nested objects. We can update name,price, category etc but need to find another method for updating stock value.

As you can see, we are not only one who faces with the problem. There are general problems with the nested object in the MongoDB & Mongoose:

Automattic/mongoose#9816
Automattic/mongoose#9803
Automattic/mongoose#9813
Automattic/mongoose#9408

We decide to postpone the stock update part. We can update all values except the attributes and stock values because of the reason that I mentioned above

### CODE REVIEW

**Review by eridincu — APPROVED** [review]

**Comment by koraycetiin** [comment]
Could you resolve the conflicts by merging the master branch

**Review by olcaytoturker — APPROVED** [review]
There is a "W" in error.js at account service. I guess it's mistakenly typed there :)

**Comment by multiminparvo** [comment]
Good catch @olcaytoturker !
Thanks :)

**Comment by multiminparvo** [comment]
Conflicts are resolved. I am merging the codes. Thanks fellas!

**Pull request merged**
